require: 
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'

Layout/LineLength:
  Enabled: false
  Max: 130

Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Naming/PredicateName:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false


