version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - netflix_network

  backend:
    container_name: netflix_backend
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - netflix_network
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
networks:
  netflix_network:

volumes:
  postgres_data:
