default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 6 } %>
  port:     5432
  host:     <%= ENV['DATABASE_HOST']     || 'localhost' %>
  username: <%= ENV['POSTGRES_USER']     || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'postgres' %>
  database: <%= ENV['DATABASE_NAME']     || "netflix_db_#{Rails.env}" %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || "netflix_db_test" %>

production:
  <<: *default
